http:
  static_dir: ./static
  templates_dir: ./templates
logging:
  console_output: true
  level: INFO
  log_file: ./logs/pyserve.log
server:
  backlog: 5
  host: 0.0.0.0  # Important: 0.0.0.0 for Docker container
  port: 8000
  redirect_instructions:
  - /home: /index.html
  - /docs: /docs.html
  reverse_proxy:
  # Examples of reverse proxy configuration
  # Uncomment and configure as needed
  # - host: test-upstream  # Name of the service in Docker network
  #   path: /api
  #   port: 80
  #   websocket: false
  # - host: localhost
  #   path: /ws
  #   port: 8080
  #   websocket: true
  #   ssl: false
  locations:
    /docs.html:
      auth:
        type: basic
        username: admin
        password: admin
ssl:
  enabled: false  # Disabled by default for simplicity
  cert_file: ./ssl/cert.pem
  key_file: ./ssl/key.pem 