
services:
  pyserve:
    build: .
    container_name: pyserve
    env_file: .env
    ports:
      - "${HTTP_PORT:-8000}:${HTTP_PORT:-8000}"
      - "${HTTPS_PORT:-8443}:${HTTPS_PORT:-8443}"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./static:/app/static
      - ./templates:/app/templates
      - pyserve-logs:/app/logs
      - ./ssl:/app/ssl:ro
    environment:
      - PYTHONPATH=/app
      - PYSERVE_PORT=${HTTP_PORT:-8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket, os; socket.create_connection(('localhost', int(os.environ.get('PYSERVE_PORT', '8000'))), timeout=3)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pyserve-network

networks:
  pyserve-network:
    driver: bridge

volumes:
  pyserve-logs:
    driver: local
